#!/usr/bin/env pwsh
# Generate dummy/stub_classes.inc — the class list the desktop dummy GDExtension
# (dummy/gdext_dummy.c) registers as empty placeholders — from the single source of
# truth: the `#[class(base = ...)]` declarations in src/*.rs.
#
# Node-derived classes get a placeholder so scenes that place them open warning-free in
# the desktop editor; non-Node classes (RefCounted etc.) are deliberately skipped so the
# ClassDB.class_exists gates in the demo scripts stay false on desktop. A base this
# script doesn't know fails the run loudly — classify it in the lists below when adding
# one to the Rust side.
#
#   pwsh scripts/gen_stub_classes.ps1          # (re)write dummy/stub_classes.inc
#   pwsh scripts/gen_stub_classes.ps1 -Check   # verify the committed file is in sync (CI)
param(
	[switch]$Check
)
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root 'dummy/stub_classes.inc'

# Base classes that inherit Node -> the dummy registers a placeholder.
$nodeBases = @('Node', 'Node2D', 'Node3D', 'Control', 'CanvasLayer')
# Known non-Node bases -> deliberately no placeholder.
$nonNodeBases = @('RefCounted', 'Object', 'Resource', 'CameraFeed')

$classes = @()
foreach ($file in Get-ChildItem (Join-Path $root 'src') -Filter '*.rs' -Recurse) {
	$text = Get-Content $file.FullName -Raw
	foreach ($m in [regex]::Matches($text, '#\[class\(([^)]*)\)\]\s*(?:pub\s+)?struct\s+(\w+)')) {
		$attrArgs = $m.Groups[1].Value
		$name = $m.Groups[2].Value
		$base = 'RefCounted'  # godot-rust's default when #[class] has no `base =`
		if ($attrArgs -match 'base\s*=\s*(\w+)') { $base = $Matches[1] }
		if ($nodeBases -contains $base) {
			$classes += [pscustomobject]@{ Name = $name; Base = $base }
		} elseif ($nonNodeBases -notcontains $base) {
			throw ("unknown base class '$base' (struct $name in $($file.Name)) — classify it " +
				'in gen_stub_classes.ps1 ($nodeBases / $nonNodeBases)')
		}
	}
}
if ($classes.Count -eq 0) {
	throw 'no Node-derived GodotClass structs found under src/ — did the parsing regex break?'
}

$lines = @(
	'/* Generated by scripts/gen_stub_classes.ps1 from the #[class(base = ...)] declarations',
	' * in the .rs sources under src/ — DO NOT EDIT. scripts/build_dummy_libs.ps1/.sh',
	' * regenerate it; CI fails when it drifts from Rust (gen_stub_classes.ps1 -Check). */',
	'static StubClass stub_classes[] = {'
)
foreach ($c in $classes | Sort-Object Name) {
	$lines += "`t{ `"$($c.Name)`", `"$($c.Base)`", 0, 0, 0 },"
}
$lines += '};'
$content = ($lines -join "`n") + "`n"

if ($Check) {
	$existing = if (Test-Path $out) { (Get-Content $out -Raw) -replace "`r", '' } else { '' }
	if ($existing -ne $content) {
		Write-Host 'dummy/stub_classes.inc is OUT OF SYNC with the #[class(base = ...)] declarations'
		Write-Host 'in src/*.rs — run scripts/gen_stub_classes.ps1 (or build_dummy_libs) and commit it.'
		exit 1
	}
	Write-Host 'stub_classes.inc is in sync.'
} else {
	[IO.File]::WriteAllText($out, $content, [Text.UTF8Encoding]::new($false))
	Write-Host "wrote dummy/stub_classes.inc ($($classes.Count) classes)"
}
