#!/usr/bin/env pwsh
# Generate dummy/stub_classes.inc — the class list the desktop dummy GDExtension
# (dummy/gdext_dummy.c) registers as empty placeholders — from the single source of
# truth: the `#[class(base = ...)]` declarations in src/*.rs.
#
# Windows script; gen_stub_classes.sh is its POSIX twin (no pwsh on mac/Linux). Keep the
# two generators' OUTPUT byte-identical — the release workflow commits whichever ran.
#
# Every GodotClass gets a placeholder: Node-derived ones so scenes that place them open
# warning-free, and the rest (RefCounted / CameraFeed) so the editor F1 help can show their
# members (the desktop dummy registers each class + its members for docs). The demo's
# real-extension gate is platform-based (OS.get_name() == "Android"), not class presence, so
# registering these on desktop is safe. A base this script doesn't know fails the run loudly —
# add it to the known list below AND in the .sh twin when adding one to the Rust side.
#
#   pwsh scripts/gen_stub_classes.ps1          # (re)write dummy/stub_classes.inc
#   pwsh scripts/gen_stub_classes.ps1 -Check   # verify the committed file is in sync
#
# build_dummy_libs.ps1 runs this before compiling (the .sh runs the .sh twin), so local
# and CI builds always use the current class list. The release workflow commits the
# regenerated file alongside the version bump (tagged vX.Y.Z), so a stale committed file
# heals with each release.
param(
	[switch]$Check
)
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root 'dummy/stub_classes.inc'

# Base classes the dummy knows how to register a placeholder for (all get one).
$knownBases = @('Node', 'Node2D', 'Node3D', 'Control', 'CanvasLayer', 'RefCounted', 'Object', 'Resource', 'CameraFeed')

$classes = @()
foreach ($file in Get-ChildItem (Join-Path $root 'src') -Filter '*.rs' -Recurse) {
	$text = Get-Content $file.FullName -Raw
	foreach ($m in [regex]::Matches($text, '#\[class\(([^)]*)\)\]\s*(?:pub\s+)?struct\s+(\w+)')) {
		$attrArgs = $m.Groups[1].Value
		$name = $m.Groups[2].Value
		$base = 'RefCounted'  # godot-rust's default when #[class] has no `base =`
		if ($attrArgs -match 'base\s*=\s*(\w+)') { $base = $Matches[1] }
		if ($knownBases -contains $base) {
			$classes += [pscustomobject]@{ Name = $name; Base = $base }
		} else {
			throw ("unknown base class '$base' (struct $name in $($file.Name)) — add it to " +
				'$knownBases in gen_stub_classes.ps1 AND the .sh twin')
		}
	}
}
if ($classes.Count -eq 0) {
	throw 'no GodotClass structs found under src/ — did the parsing regex break?'
}

$lines = @(
	'/* Generated by scripts/gen_stub_classes.ps1 (Windows) / gen_stub_classes.sh (mac/Linux)',
	' * from the #[class(base = ...)] declarations in the .rs sources under src/ — DO NOT',
	' * EDIT. build_dummy_libs regenerates it; releases commit the regenerated file. */',
	'static StubClass stub_classes[] = {'
)
# Ordinal sort, matching the .sh twin's LC_ALL=C sort byte-for-byte.
$sorted = @($classes)
[Array]::Sort($sorted, [System.Comparison[object]] { param($a, $b) [string]::CompareOrdinal($a.Name, $b.Name) })
foreach ($c in $sorted) {
	$lines += "`t{ `"$($c.Name)`", `"$($c.Base)`", 0, 0, 0 },"
}
$lines += '};'
$content = ($lines -join "`n") + "`n"

if ($Check) {
	$existing = if (Test-Path $out) { (Get-Content $out -Raw) -replace "`r", '' } else { '' }
	if ($existing -ne $content) {
		Write-Host 'dummy/stub_classes.inc is OUT OF SYNC with the #[class(base = ...)] declarations'
		Write-Host 'in src/*.rs — run scripts/gen_stub_classes.ps1 (or build_dummy_libs) and commit it.'
		exit 1
	}
	Write-Host 'stub_classes.inc is in sync.'
} else {
	[IO.File]::WriteAllText($out, $content, [Text.UTF8Encoding]::new($false))
	Write-Host "wrote dummy/stub_classes.inc ($($classes.Count) classes)"
}
