#!/usr/bin/env bash
# Generate dummy/stub_classes.inc — the class list the desktop dummy GDExtension
# (dummy/gdext_dummy.c) registers as empty placeholders — from the single source of
# truth: the `#[class(base = ...)]` declarations in the .rs sources under src/.
#
# POSIX twin of gen_stub_classes.ps1 (Windows; no pwsh on mac/Linux). Keep the two
# generators' OUTPUT byte-identical — the release workflow commits whichever ran.
#
# Node-derived classes get a placeholder so scenes that place them open warning-free in
# the desktop editor; non-Node classes (RefCounted etc.) are deliberately skipped so the
# ClassDB.class_exists gates in the demo scripts stay false on desktop. A base this
# script doesn't know fails the run loudly — classify it below AND in the .ps1 twin.
#
#   ./scripts/gen_stub_classes.sh            # (re)write dummy/stub_classes.inc
#   ./scripts/gen_stub_classes.sh --check    # verify the committed file is in sync
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/dummy/stub_classes.inc"

# Base classes that inherit Node -> the dummy registers a placeholder.
node_bases="Node Node2D Node3D Control CanvasLayer"
# Known non-Node bases -> deliberately no placeholder.
non_node_bases="RefCounted Object Resource CameraFeed"

pairs_file="$(mktemp)"
entries_file="$(mktemp)"
content_file="$(mktemp)"
trap 'rm -f "$pairs_file" "$entries_file" "$content_file"' EXIT

# "Name Base" per matched struct. `#[class(...)]` and its struct sit on adjacent lines in
# practice; scan forward to the next struct to be safe (reset at file boundaries).
find "$root/src" -type f -name '*.rs' | LC_ALL=C sort | while IFS= read -r f; do
	awk '
		FNR == 1 { pending = 0 }
		/#\[class\(/ {
			cls_args = $0
			sub(/.*#\[class\(/, "", cls_args); sub(/\)\].*/, "", cls_args)
			pending = 1; next
		}
		pending && /struct[ \t]+[A-Za-z0-9_]+/ {
			name = $0
			sub(/.*struct[ \t]+/, "", name); sub(/[^A-Za-z0-9_].*/, "", name)
			base = "RefCounted"  # godot-rust default when #[class] has no `base =`
			if (match(cls_args, /base[ \t]*=[ \t]*[A-Za-z0-9_]+/)) {
				base = substr(cls_args, RSTART, RLENGTH)
				sub(/.*=[ \t]*/, "", base)
			}
			print name " " base
			pending = 0
		}
	' "$f" >> "$pairs_file"
done

count=0
while IFS=' ' read -r name base; do
	[ -n "$name" ] || continue
	case " $node_bases " in
	*" $base "*)
		printf '\t{ "%s", "%s", 0, 0, 0 },\n' "$name" "$base" >> "$entries_file"
		count=$((count + 1))
		;;
	*)
		case " $non_node_bases " in
		*" $base "*) ;;
		*)
			echo "error: unknown base class '$base' (struct $name) — classify it in" >&2
			echo "gen_stub_classes.sh (node_bases / non_node_bases) AND the .ps1 twin" >&2
			exit 1
			;;
		esac
		;;
	esac
done < <(LC_ALL=C sort "$pairs_file")
if [ "$count" -eq 0 ]; then
	echo "error: no Node-derived GodotClass structs found under src/ — did the parsing break?" >&2
	exit 1
fi

{
	printf '%s\n' \
		'/* Generated by scripts/gen_stub_classes.ps1 (Windows) / gen_stub_classes.sh (mac/Linux)' \
		' * from the #[class(base = ...)] declarations in the .rs sources under src/ — DO NOT' \
		' * EDIT. build_dummy_libs regenerates it; releases commit the regenerated file. */' \
		'static StubClass stub_classes[] = {'
	cat "$entries_file"
	printf '%s\n' '};'
} > "$content_file"

if [ "${1:-}" = "--check" ]; then
	if cmp -s "$content_file" "$out"; then
		echo "stub_classes.inc is in sync."
	else
		echo "dummy/stub_classes.inc is OUT OF SYNC with the #[class(base = ...)] declarations" >&2
		echo "in src/ — run scripts/gen_stub_classes.sh (or build_dummy_libs) and commit it." >&2
		exit 1
	fi
else
	cp "$content_file" "$out"
	echo "wrote dummy/stub_classes.inc ($count classes)"
fi
